name: Generate Release Notes

on:
  release:
    types:
      - created

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g conventional-changelog-cli

      - name: Generate Release Notes
        run: |
          # Get the latest tag and the current tag
          latestTag=$(git describe --tags $(git rev-list --tags --max-count=1))
          currentTag=$(git describe --tags)

          # Generate release notes
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0 -t "${latestTag}" -v "${currentTag}"

          # Exclude certain users from release notes
          sed -i '/<exclude-user-1>/d' CHANGELOG.md
          sed -i '/<exclude-user-2>/d' CHANGELOG.md

          # Commit the updated release notes
          git add CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "chore: update release notes [skip ci]"

      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}