name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g conventional-changelog-cli

      - name: Fetch tags
        run: git fetch --tags

      - name: Generate Release Notes
        run: |
          # Get the latest tag and the current tag
          latestTag=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | head -n 1)
          currentTag=$(git describe --tags --always)
          echo "Latest Tag: $latestTag"
          echo "Current Tag: $currentTag"
          if [ -z "$latestTag" ]; then
            echo "No previous tags found."
            exit 1
          fi
          if [ -z "$currentTag" ]; then
            echo "No current tags found."
            exit 1
          fi

          # Generate release notes
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0 -t "${latestTag}" -v "${currentTag}"

          # Exclude certain users from release notes
          sed -i '/<exclude-user-1>/d' CHANGELOG.md
          sed -i '/<exclude-user-2>/d' CHANGELOG.md

          # Commit the updated release notes
          git add CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "chore: update release notes [skip ci]"

      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}