name: "Release"

on:
  push:
    tags:
      - "v*.*.*" # Match tags that start with 'v'
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for automatic release
        required: true

jobs:
  changelog:
    exclude:
      authors:
        - ludovico-bot
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false