name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        id: release-notes
        uses: github/docs
        # This should point to the version you want to use

      - name: Display Release Notes
        run: echo "${{ steps.release-notes.outputs.release-notes }}"